# Generated by Django 4.1.1 on 2022-09-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.vendor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.customer')),
                ("product", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
