# Generated by Django 4.1.1 on 2022-09-07 04:04
from random import uniform

from django.db import migrations


def populate_test_data(apps, schema_editor):
    Vendor = apps.get_model('django_project', 'Vendor')
    Customer = apps.get_model('django_project', 'Customer')
    Purchase = apps.get_model('django_project', 'Purchase')

    vendors = [
        Vendor(name='Иван', surname='Иванов', phone='+7 913 8225 88 67', salary=60000),
        Vendor(name='Ибрагим', surname='Иванов', phone='+7 913 8225 88 68', salary=60000),
        Vendor(name='Екатерина', surname='Петрова', phone='+7 913 8225 88 69', salary=60000),
    ]
    Vendor.objects.bulk_create(vendors)

    customers = [
        Customer(name='Александр', phone='+7 913 8225 88 67'),
        Customer(name='Кир', phone='+7 913 8225 88 67'),
        Customer(name='Филипп', phone='+7 913 8225 88 67'),
        Customer(name='Сергей', phone='+7 913 8225 88 67'),
        Customer(name='Евгений', phone='+7 913 8225 88 67'),
    ]

    Customer.objects.bulk_create(customers)

    purchases = (
        Purchase(vendor=vendor, customer=customer, product='Продукт ' + str(int(uniform(1, 3))), quantity=uniform(1, 5), price=uniform(100, 1000))
        for vendor in vendors
        for customer in customers
    )
    Purchase.objects.bulk_create(purchases)


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0003_purchase'),
    ]

    operations = [
        migrations.RunPython(populate_test_data),
    ]
